version: '3.2'

services:
  explorer-api:
    build: explorer-api/.
    image: polkascan/pre-explorer-api:latest
    volumes:
      - './explorer-api:/usr/src/app'
    command: ./start.sh
    environment:
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=prod
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=polkascan
      - SUBSTRATE_RPC_URL=http://node-template-spartan:9933/
      - SUBSTRATE_ADDRESS_TYPE=42
      - TYPE_REGISTRY_FILE=app/type_registry/custom_types.json
      - SUBSTRATE_METADATA_VERSION=13
    depends_on:
      - mysql
      - node-template-spartan

  harvester-api:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    hostname: harvester-api
    volumes:
      - './harvester:/usr/src/app'
    command: ./start.sh
    environment: &env
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/usr/src/app:/usr/src/app/py-substrate-interface/:/usr/src/app/py-scale-codec/
      - ENVIRONMENT=prod
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=polkascan
      - SUBSTRATE_RPC_URL=http://node-template-spartan:9933/
      - TYPE_REGISTRY_FILE=app/type_registry/custom_types.json
      - SUBSTRATE_ADDRESS_TYPE=42
      - SUBSTRATE_METADATA_VERSION=13
      - NEW_SESSION_EVENT_HANDLER=True
      - SUBSTRATE_STORAGE_BALANCE=Account
      - SUBSTRATE_STORAGE_INDICES=Accounts
      - FINALIZATION_ONLY=0
    depends_on:
      - redis
      - mysql
      - node-template-spartan

  harvester-worker:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
    command: celery -A app.tasks worker --loglevel=INFO
    environment: *env
    depends_on:
      - redis
      - mysql

  harvester-beat:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
      - '/usr/src/app/data'
    command: celery -A app.tasks beat --loglevel=INFO  --schedule="data/celerybeat-schedule" --pidfile="data/celerybeat.pid"
    environment: *env
    depends_on:
      - redis

  harvester-monitor:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    environment: *env
    ports:
      - '5555:5555'
    command: flower -A app.tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:3.2.11
    hostname: redis

  mysql:
    image: mysql:8.0.23
    hostname: mysql
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '33061:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polkascan

  node-template-spartan:
    image: subspacelabs/node-template-spartan
    hostname: node-template-spartan
    volumes:
      - 'substrate-data:/var/spartan'
    ports:
      - '30333:30333'
      - '9933:9933'
      - '9944:9944'
    command: --dev --base-path /var/spartan --rpc-external --rpc-cors=all --ws-external --rpc-methods=Unsafe --pruning=archive --bootnodes /ip4/165.232.157.230/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp --telemetry-url "wss://telemetry.polkadot.io/submit/ 9"

  explorer-gui:
    image: polkascan/pre-explorer-gui:latest
    build:
      context: explorer-gui/.
      args:
        NETWORK_NAME: Spartan testnet
        NETWORK_ID: dev
        NETWORK_TYPE: pre
        CHAIN_TYPE: para
        NETWORK_TOKEN_SYMBOL: DEV
        NETWORK_TOKEN_DECIMALS: 12
        NETWORK_COLOR_CODE: f19135
        API_URL: http://127.0.0.1:8080/api/v1
    ports:
      - '8080:80'
    depends_on:
      - harvester-api
      - explorer-api

volumes:
  db-data:
  substrate-data:
